{% set name = "expects" %}
{% set version = "0.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/expects-{{ version }}.tar.gz
  sha256: 419902ccafe81b7e9559eeb6b7a07ef9d5c5604eddb93000f0642b3b2d594f4c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - expects
    - expects.matchers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jaimegildesagredo/expects
  summary: Expressive and extensible TDD/BDD assertion library for Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kyri-petrou
